"""
Postgres store for SKU-comparison runs, reviews, the watchlist, and the learned
`confirmed_matches` memory.

Backed by the SHARED app database (Neon Postgres) so local and prod read/write the
SAME store — a match confirmed locally is trusted on a prod compare, and run/review
history is one place. (Previously a per-machine SQLite file, which diverged between
environments.) The public API is unchanged — every function keeps its old signature,
so callers don't change.

Stand-alone (no app imports beyond settings) so it never causes import cycles. We
open a fresh psycopg connection per call against Neon's `-pooler` endpoint (server
-side PgBouncer), which makes short connections cheap and avoids any client-side
pool / background-thread / stale-connection complexity — and behaves identically on
macOS (local) and Linux (prod). Schema is self-created on first use (it was never
part of the alembic migrations); CREATE … IF NOT EXISTS makes that idempotent.
"""
from __future__ import annotations

import json
import threading
from contextlib import contextmanager
from typing import Any, Iterator

import psycopg
from psycopg.rows import dict_row

from app.settings import get_settings

# Postgres DDL — mirrors the historical SQLite schema. AUTOINCREMENT → IDENTITY
# (GENERATED BY DEFAULT so the one-time data import can keep the original ids).
_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS runs (
        id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        started_at    text NOT NULL,
        finished_at   text,
        status        text NOT NULL,            -- running | done | error
        trigger       text NOT NULL,            -- scheduled | manual | rerun
        sku_count     integer DEFAULT 0,
        done_count    integer DEFAULT 0,
        error         text,
        source_run_id bigint                    -- when trigger=rerun, the run it copied
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS watchlist (
        sku      text PRIMARY KEY,
        name     text NOT NULL,
        added_at text
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS run_items (
        id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id  bigint NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
        idx     integer NOT NULL,
        sku     text,
        name    text,
        result  text,                           -- CompareResult JSON
        UNIQUE(run_id, idx)
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_run_items_run ON run_items(run_id)",
    """
    CREATE TABLE IF NOT EXISTS reviews (
        id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at  text NOT NULL,
        product     text NOT NULL,              -- input product name reviewed
        dk_matched  text,                       -- what DK resolved to (for context)
        correct     integer NOT NULL,           -- 1 = reviewer says correct, 0 = needs fix
        message     text,                       -- improvement note when not correct
        result      text,                       -- full CompareResult JSON snapshot
        run_id      bigint                      -- the scheduled run reviewed (else NULL)
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_reviews_correct ON reviews(correct)",
    """
    CREATE TABLE IF NOT EXISTS confirmed_matches (
        id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        dk_key        text NOT NULL,            -- normalized DK product name (the lookup key)
        competitor_id text NOT NULL,
        label         text NOT NULL,            -- correct | no_match
        matched_url   text,                     -- confirmed PDP url (NULL for no_match)
        matched_name  text,
        source        text,                     -- review | feedback | golden
        updated_at    text NOT NULL,
        UNIQUE(dk_key, competitor_id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_confirmed_key ON confirmed_matches(dk_key)",
]

_initialized = False
_lock = threading.Lock()
_shared_conn: Any = None
_conn_lock = threading.RLock()


@contextmanager
def _conn() -> Iterator[Any]:
    """ONE process-wide psycopg connection, REUSED across all requests and serialized
    by a lock. A fresh connect to a remote Neon (another region, occasionally a flaky
    pooler IP) costs ~0.3-30s — paying that per request (or even per worker thread)
    made every /runs refresh slow. With a single shared connection we connect ~once;
    every call after is just the query (~0.1-0.7s). The lock serialises access
    (psycopg connections aren't concurrency-safe) — fine for this low-traffic store.
    A stale connection (Neon idle-dropped it) is discarded so the next call reconnects.
    connect_timeout bounds a cold start / unreachable IP so a bad connect can't hang
    forever."""
    global _shared_conn
    with _conn_lock:
        if _shared_conn is None or _shared_conn.closed:
            # keepalives + tcp_user_timeout make the OS notice a dead/stalled socket
            # in ~15s instead of hanging for minutes; statement_timeout bounds a slow
            # query. So a flaky network fails FAST (then reconnects) rather than
            # freezing the page.
            _shared_conn = psycopg.connect(
                get_settings().database_url, row_factory=dict_row,
                connect_timeout=12, keepalives=1, keepalives_idle=15,
                keepalives_interval=5, keepalives_count=3, tcp_user_timeout=15000,
                options="-c statement_timeout=15000")
        conn = _shared_conn
        try:
            with conn.transaction():
                yield conn
        except (psycopg.OperationalError, psycopg.InterfaceError):
            try:
                conn.close()
            except Exception:
                pass
            _shared_conn = None
            raise


def init_db() -> None:
    """Create the schema if absent. Idempotent and cheap after the first call
    (guarded so the DDL round-trip doesn't run on every request)."""
    global _initialized
    if _initialized:
        return
    with _lock:
        if _initialized:
            return
        with _conn() as c:
            for stmt in _SCHEMA:
                c.execute(stmt)
        _initialized = True


def create_run(started_at: str, trigger: str, sku_count: int,
               source_run_id: int | None = None) -> int:
    with _conn() as c:
        row = c.execute(
            "INSERT INTO runs (started_at, status, trigger, sku_count, source_run_id) "
            "VALUES (%s,%s,%s,%s,%s) RETURNING id",
            (started_at, "running", trigger, sku_count, source_run_id),
        ).fetchone()
        return int(row["id"])


# ── watchlist (the fixed products kept in every run for price tracking) ──
def get_watchlist() -> list[dict[str, Any]]:
    with _conn() as c:
        return [dict(r) for r in c.execute(
            "SELECT sku, name FROM watchlist ORDER BY added_at, sku").fetchall()]


def set_watchlist(items: list[dict[str, str]], added_at: str) -> None:
    with _conn() as c:
        c.execute("DELETE FROM watchlist")
        with c.cursor() as cur:
            cur.executemany(
                "INSERT INTO watchlist (sku, name, added_at) VALUES (%s,%s,%s) "
                "ON CONFLICT (sku) DO UPDATE SET name=excluded.name, added_at=excluded.added_at",
                [(i["sku"], i["name"], added_at) for i in items],
            )


def add_to_watchlist(items: list[dict[str, str]], added_at: str) -> None:
    with _conn() as c, c.cursor() as cur:
        cur.executemany(
            "INSERT INTO watchlist (sku, name, added_at) VALUES (%s,%s,%s) "
            "ON CONFLICT (sku) DO NOTHING",
            [(i["sku"], i["name"], added_at) for i in items],
        )


def save_item(run_id: int, idx: int, sku: str, name: str, result: dict[str, Any]) -> None:
    with _conn() as c:
        c.execute(
            "INSERT INTO run_items (run_id, idx, sku, name, result) VALUES (%s,%s,%s,%s,%s) "
            "ON CONFLICT (run_id, idx) DO UPDATE SET "
            "sku=excluded.sku, name=excluded.name, result=excluded.result",
            (run_id, idx, sku, name, json.dumps(result)),
        )
        c.execute("UPDATE runs SET done_count = done_count + 1 WHERE id=%s", (run_id,))


def finish_run(run_id: int, finished_at: str, status: str, error: str | None = None) -> None:
    with _conn() as c:
        c.execute(
            "UPDATE runs SET finished_at=%s, status=%s, error=%s WHERE id=%s",
            (finished_at, status, error, run_id),
        )


def list_runs(limit: int = 200) -> list[dict[str, Any]]:
    with _conn() as c:
        rows = c.execute(
            "SELECT * FROM runs ORDER BY id DESC LIMIT %s", (limit,)
        ).fetchall()
        # Batch the per-run review summaries in ONE query (avoid an N+1 round-trip
        # to the remote DB for every run).
        ids = [r["id"] for r in rows]
        summ = c.execute(
            "SELECT run_id, COUNT(*) total, COALESCE(SUM(correct),0) correct "
            "FROM reviews WHERE run_id = ANY(%s) GROUP BY run_id", (ids,)
        ).fetchall() if ids else []
    smap = {s["run_id"]: s for s in summ}
    out = []
    for r in rows:
        d = dict(r)
        s = smap.get(d["id"])
        total = int(s["total"]) if s else 0
        correct = int(s["correct"]) if s else 0
        d["review"] = {"reviewed": total, "correct": correct,
                       "accuracy": round(100.0 * correct / total, 1) if total else None}
        out.append(d)
    return out


def get_run(run_id: int) -> dict[str, Any] | None:
    with _conn() as c:
        run = c.execute("SELECT * FROM runs WHERE id=%s", (run_id,)).fetchone()
        if run is None:
            return None
        items = c.execute(
            "SELECT idx, sku, name, result FROM run_items WHERE run_id=%s ORDER BY idx",
            (run_id,),
        ).fetchall()
    out = dict(run)
    out["review"] = run_review_summary(run_id)
    out["items"] = [
        {"idx": it["idx"], "sku": it["sku"], "name": it["name"],
         "result": json.loads(it["result"]) if it["result"] else None}
        for it in items
    ]
    return out


def price_history(name: str) -> list[dict[str, Any]]:
    """Every stored price point for a product (by name), oldest first — DK +
    each competitor (shown matches only) per run that included it. Powers the
    per-product price-change view."""
    with _conn() as c:
        rows = c.execute(
            "SELECT r.id run_id, r.started_at, i.result "
            "FROM run_items i JOIN runs r ON r.id = i.run_id "
            "WHERE i.name = %s AND i.result IS NOT NULL ORDER BY r.started_at",
            (name,),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        try:
            res = json.loads(row["result"])
        except (TypeError, ValueError):
            continue
        dk = res.get("dentalkart_match") or {}
        comps = {
            c["competitor_id"]: c.get("matched_price")
            for c in res.get("competitors", [])
            if c.get("matched_name") and (c.get("score") or 0) >= 0.7 and c.get("matched_price")
        }
        out.append({
            "run_id": row["run_id"], "time": row["started_at"],
            "dk_price": dk.get("matched_price"), "competitors": comps,
        })
    return out


def save_review(created_at: str, product: str, dk_matched: str | None,
                correct: bool, message: str | None, result: dict[str, Any] | None,
                run_id: int | None = None) -> int:
    with _conn() as c:
        row = c.execute(
            "INSERT INTO reviews (created_at, product, dk_matched, correct, message, result, run_id) "
            "VALUES (%s,%s,%s,%s,%s,%s,%s) RETURNING id",
            (created_at, product, dk_matched, 1 if correct else 0, message,
             json.dumps(result) if result is not None else None, run_id),
        ).fetchone()
        return int(row["id"])


def run_review_summary(run_id: int) -> dict[str, Any]:
    with _conn() as c:
        row = c.execute(
            "SELECT COUNT(*) total, COALESCE(SUM(correct),0) correct FROM reviews WHERE run_id=%s",
            (run_id,),
        ).fetchone()
    total = int(row["total"]); correct = int(row["correct"])
    return {"reviewed": total, "correct": correct,
            "accuracy": round(100.0 * correct / total, 1) if total else None}


def list_reviews(limit: int = 1000, only_issues: bool = False) -> list[dict[str, Any]]:
    q = "SELECT id, created_at, product, dk_matched, correct, message FROM reviews"
    if only_issues:
        q += " WHERE correct = 0"
    q += " ORDER BY id DESC LIMIT %s"
    with _conn() as c:
        return [dict(r) for r in c.execute(q, (limit,)).fetchall()]


def review_summary() -> dict[str, Any]:
    with _conn() as c:
        row = c.execute(
            "SELECT COUNT(*) total, COALESCE(SUM(correct),0) correct FROM reviews"
        ).fetchone()
    total = int(row["total"]); correct = int(row["correct"])
    return {"total": total, "correct": correct,
            "accuracy": round(100.0 * correct / total, 1) if total else None}


# ── confirmed matches (the learned memory) ───────────────────────────────────
# Once a human confirms (or corrects) a product↔competitor match, we remember it
# keyed by the NORMALIZED dk name (caller supplies the key). On later runs the
# matcher trusts this instead of re-discovering. We store the LINK, not the price
# (price is re-scraped fresh each time), plus negative "no_match" truths.

def upsert_confirmed(dk_key: str, competitor_id: str, label: str,
                     matched_url: str | None, matched_name: str | None,
                     source: str, updated_at: str) -> None:
    """Remember a confirmed truth for (dk_key, competitor). label='correct' stores
    the confirmed url; label='no_match' remembers there is none. Re-confirming
    overwrites the previous answer."""
    with _conn() as c:
        c.execute(
            "INSERT INTO confirmed_matches "
            "(dk_key, competitor_id, label, matched_url, matched_name, source, updated_at) "
            "VALUES (%s,%s,%s,%s,%s,%s,%s) "
            "ON CONFLICT(dk_key, competitor_id) DO UPDATE SET "
            "label=excluded.label, matched_url=excluded.matched_url, "
            "matched_name=excluded.matched_name, source=excluded.source, "
            "updated_at=excluded.updated_at",
            (dk_key, competitor_id, label, matched_url, matched_name, source, updated_at),
        )


def clear_confirmed(dk_key: str, competitor_id: str) -> None:
    """Forget a confirmation (e.g. a 👎 says the remembered match is now wrong) so
    the matcher reverts to live discovery for that cell."""
    with _conn() as c:
        c.execute("DELETE FROM confirmed_matches WHERE dk_key=%s AND competitor_id=%s",
                  (dk_key, competitor_id))


def get_confirmed(dk_key: str) -> dict[str, dict[str, Any]]:
    """All confirmed truths for a product → {competitor_id: {label, matched_url,
    matched_name, updated_at}}. Empty when nothing is remembered."""
    with _conn() as c:
        rows = c.execute(
            "SELECT competitor_id, label, matched_url, matched_name, updated_at "
            "FROM confirmed_matches WHERE dk_key=%s", (dk_key,)).fetchall()
    return {r["competitor_id"]: dict(r) for r in rows}


def confirmed_count() -> int:
    with _conn() as c:
        return int(c.execute("SELECT COUNT(*) FROM confirmed_matches").fetchone()["count"])


def prune(retention_days: int) -> int:
    """Delete runs older than retention_days (by started_at). Returns #deleted.
    run_items go with them via ON DELETE CASCADE."""
    with _conn() as c:
        cur = c.execute(
            "DELETE FROM runs WHERE started_at::timestamptz < now() - make_interval(days => %s)",
            (int(retention_days),),
        )
        return cur.rowcount


def delete_run(run_id: int) -> bool:
    """Permanently delete one run and its items + reviews. Returns True if a run
    was removed. (run_items cascade on the run delete; reviews have no FK.)"""
    with _conn() as c:
        cur = c.execute("DELETE FROM runs WHERE id=%s", (run_id,))
        c.execute("DELETE FROM reviews WHERE run_id=%s", (run_id,))
        return cur.rowcount > 0
